# Generated by Django 3.1.2 on 2020-10-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(to='employee_app.Department'),
        ),
    ]
