# Generated by Django 3.1.2 on 2020-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='dept', to='employee_app.Department'),
        ),
    ]
