# Generated by Django 3.1.2 on 2020-10-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_auto_20201007_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(related_name='dept', to='employee_app.Department'),
        ),
    ]
