# Generated by Django 3.1.2 on 2020-10-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_auto_20201006_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designationName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(related_name='dept', to='employee_app.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.designation'),
        ),
    ]
