# Generated by Django 3.1.2 on 2020-10-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_auto_20201012_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='employee_app.Department'),
        ),
    ]
