# Generated by Django 3.1.2 on 2020-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20201014_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, to='employee_app.Department'),
        ),
    ]
