# Generated by Django 3.1.2 on 2020-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_auto_20201022_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='emp', to='employee_app.Department'),
        ),
    ]
